const monthlyData = {
  August: [
    {
      day: 1,
      etransfer: "2000",
      toronto: { description: "Labour (1 week)", paid: 300, remaining: 0 },
      hamilton: { description: "Labour", paid: 665, remaining: 0 },
      miscellaneous: { description: "Taiba", paid: 1200, remaining: 0 },
    },
    {
      day: 3,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "Storage", paid: 675.83, remaining: 0 },
    },
    {
      day: 5,
      etransfer: "7000",
      toronto: { description: "Old framing", paid: 1500, remaining: 0 },
      hamilton: { description: "Taha", paid: 2000, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 6,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: {
        description: "Interest Charge",
        paid: 165.03,
        remaining: 0,
      },
    },
    {
      day: 7,
      etransfer: "5000",
      toronto: { description: "Electrician", paid: 500, remaining: 0 },
      hamilton: { description: "Framing", paid: 5000, remaining: 0 },
      miscellaneous: { description: "overlimit fee", paid: 29, remaining: 0 },
    },
    {
      day: 8,
      etransfer: "0",
      toronto: { description: "flooring material", paid: 335, remaining: 0 },
      hamilton: {
        description: "partition wall/wood",
        paid: 2000,
        remaining: 0,
      },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 11,
      etransfer: "0",
      toronto: { description: "taha", paid: 2500, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 12,
      etransfer: "5000",
      toronto: { description: "flooring fix", paid: 1500, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
  ],
  July: [
    {
      day: 1,
      etransfer: "5000",
      toronto: {
        description: "Vinyl flooring cash & floor material",
        paid: 3450,
        remaining: 0,
      },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 2,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "Taiba", paid: 1500, remaining: 0 },
    },
    {
      day: 3,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 4,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "Storage", paid: 675, remaining: 0 },
    },
    {
      day: 5,
      etransfer: "5000",
      toronto: {
        description: "Kitchen Tbar ceiling & Electrician",
        paid: 3000,
        remaining: 0,
      },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 6,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 7,
      etransfer: "0",
      toronto: { description: "Paint's final", paid: 800, remaining: 0 },
      hamilton: { description: "Taiba", paid: 500, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 8,
      etransfer: "5000",
      toronto: { description: "Labour (3 months)", paid: 2315, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 9,
      etransfer: "0",
      toronto: { description: "Labour (3Days)", paid: 70, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 10,
      etransfer: "0",
      toronto: { description: "Labour (2 days)", paid: 484, remaining: 0 },
      hamilton: { description: "Labour (3 days)", paid: 500, remaining: 0 },
      miscellaneous: {
        description: "Office material and labour",
        paid: 975.98,
        remaining: 0,
      },
    },
    {
      day: 11,
      etransfer: "5000",
      toronto: { description: "Electrician", paid: 2500, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 12,
      etransfer: "0",
      toronto: { description: "Plumber", paid: 1900, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 13,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 14,
      etransfer: "0",
      toronto: { description: "Electrician", paid: 600, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 15,
      etransfer: "0",
      toronto: { description: "Baseboard", paid: 500, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 16,
      etransfer: "5000",
      toronto: { description: "New wall", paid: 2200, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "Taiba's cc", paid: 1500, remaining: 0 },
    },
    {
      day: 17,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 18,
      etransfer: "0",
      toronto: { description: "Cooler/Freezer", paid: 960, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 19,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 20,
      etransfer: "1500",
      toronto: {
        description: "Labour (8 hrs) (2 people)",
        paid: 240,
        remaining: 0,
      },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 21,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "Walls", paid: 500, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 22,
      etransfer: "0",
      toronto: { description: "Labour (3 days)", paid: 600, remaining: 0 },
      hamilton: { description: "Walls/Framing", paid: 1000, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 23,
      etransfer: "2000",
      toronto: {
        description: "Labour (9 hrs) (2 people)",
        paid: 270,
        remaining: 0,
      },
      hamilton: { description: "Walls", paid: 500, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 24,
      etransfer: "0",
      toronto: { description: "Labour (26hrs)", paid: 390, remaining: 0 },
      hamilton: { description: "Labour (3 days)", paid: 305.5, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 25,
      etransfer: "2000",
      toronto: { description: "Framing", paid: 2000, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 26,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 27,
      etransfer: "5000",
      toronto: { description: "Labour", paid: 1500, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 28,
      etransfer: "0",
      toronto: { description: "Labour (3 days)", paid: 580, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 29,
      etransfer: "0",
      toronto: { description: "", paid: 0, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "Storage", paid: 675, remaining: 0 },
    },
    {
      day: 30,
      etransfer: "0",
      toronto: { description: "Remaining labour", paid: 80, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: { description: "", paid: 0, remaining: 0 },
    },
    {
      day: 31,
      etransfer: "0",
      toronto: { description: "Remaining labour", paid: 100, remaining: 0 },
      hamilton: { description: "", paid: 0, remaining: 0 },
      miscellaneous: {
        description: "Labour (2 days)",
        paid: 200,
        remaining: 0,
      },
    },
  ],
  June: [
    {
      day: 3,
      etransfer: "",
      toronto: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "storage",
        paid: 675.83,
        remaining: 0,
      },
    },

    {
      day: 5,
      etransfer: "5000",
      toronto: {
        description: "framing",
        paid: 500,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 6,
      etransfer: "",
      toronto: {
        description: "labour",
        paid: 900,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "KP Oakville, furniture delivery payment",
        paid: 450,
        remaining: 0,
      },
    },
    {
      day: 7,
      etransfer: "",
      toronto: {
        description: "framing materials",
        paid: 500,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "winger labour, fixed washrooms",
        paid: 256,
        remaining: 0,
      },
    },

    {
      day: 9,
      etransfer: "",
      toronto: {
        description: "2x glass window cut",
        paid: 1200,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },

    {
      day: 11,
      etransfer: "5000",
      toronto: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 12,
      etransfer: "",
      toronto: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      hamilton: {
        description: "light bulbs",
        paid: 1830.6,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 13,
      etransfer: "",
      toronto: {
        description: "framing materials",
        paid: 500,
        remaining: 0,
      },
      hamilton: {
        description: "walls",
        paid: 500,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 14,
      etransfer: "2500",
      toronto: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "taiba",
        paid: 2500,
        remaining: 0,
      },
    },
    {
      day: 18,
      etransfer: "5000",
      toronto: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      hamilton: {
        description: "framing(cash)",
        paid: 5000,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 19,
      etransfer: "",
      toronto: {
        description: "scissor lift",
        paid: 621.5,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 20,
      etransfer: "5000",
      toronto: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "taiba cc",
        paid: 1000,
        remaining: 0,
      },
    },
    {
      day: 21,
      etransfer: "",
      toronto: {
        description: "walls",
        paid: 1500,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 22,
      etransfer: "",
      toronto: {
        description: "8 days labour ",
        paid: 1600,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 23,
      etransfer: "",
      toronto: {
        description: "framing materials",
        paid: 775,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 23,
      etransfer: "4000",
      toronto: {
        description: "35 hours labour",
        paid: 550,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "taiba cc",
        paid: 1500,
        remaining: 0,
      },
    },
    {
      day: 24,
      etransfer: "",
      toronto: {
        description: "framing guy",
        paid: 1500,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 25,
      etransfer: "5000",
      toronto: {
        description: "electrician lights",
        paid: 1000,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 26,
      etransfer: "",
      toronto: {
        description: "scissors lift",
        paid: 265,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 26,
      etransfer: "",
      toronto: {
        description: "plumber",
        paid: 2000,
        remaining: 0,
      },
      hamilton: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 27,
      etransfer: "",
      toronto: {
        description: "Tbar ceiling",
        paid: 1500,
        remaining: 0,
      },
      hamilton: {
        description: "1200",
        paid: 1200,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
    {
      day: 28,
      etransfer: "5000",
      toronto: {
        description: "",
        paid: 0,
        remaining: 0,
      },
      hamilton: {
        description: "hamilton framing 2nd",
        paid: 5000,
        remaining: 0,
      },
      miscellaneous: {
        description: "",
        paid: 0,
        remaining: 0,
      },
    },
  ],
};

export default monthlyData;
